In [28]:
import numpy as np 
beta = np.array([2,3,7]) # 3
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) # (4,3)
y = np.array([11,22,33, 44])# 3
lmda = 0.1

In [29]:
tmp = y - x.dot(beta) 
tmp

array([-18, -43, -68, -93])

In [33]:
first_term = -2 * x.T.dot(tmp) # expect (3)
first_term

array([3192, 3636, 4080])

In [34]:
penalty = 2 * lmda * beta
penalty

array([0.4, 0.6, 1.4])

In [35]:
first_term + penalty

array([3192.4, 3636.6, 4081.4])

In [37]:
((y-x.dot(beta)) ** 2)

array([ 324, 1849, 4624, 8649], dtype=int32)

In [38]:
((y-x.dot(beta)) ** 2).sum(axis=0) + 

15446

In [40]:
x.sum(axis=0)

array([22, 26, 30])

In [41]:
np.random.randn(5)

array([-2.26658989,  1.73527016,  0.57246381,  1.09598458,  0.09983674])

In [44]:
from numpy import * 
one_hot = np.array([0,1,1,0,1,0])
(one_hot - mean(one_hot))/std(one_hot)

array([-1.,  1.,  1., -1.,  1., -1.])

array([7, 8, 9])

In [57]:
tmp = np.array([4,2,5,1])
ind = np.argsort(tmp.reshape(-1))

In [58]:
tmp[ind]

array([1, 2, 4, 5])

In [59]:
mean([1,2,3,4])

2.5

In [70]:
tmp = np.hstack((tmp,tmp))

In [71]:
tmp

array([4, 2, 5, 1, 4, 2, 5, 1])